# Generated by Django 2.0.5 on 2018-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('time_limit', models.FloatField()),
                ('memory_limit', models.FloatField()),
                ('submissions', models.IntegerField(default=0)),
                ('accpected', models.IntegerField(default=0)),
            ],
        ),
    ]
