# Generated by Django 2.0.5 on 2018-05-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.FloatField(default=256.0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0),
        ),
    ]
