# Generated by Django 2.0.5 on 2018-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180525_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
    ]
