# Generated by Django 2.0.5 on 2018-06-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='accpected',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='submissions',
        ),
    ]
