# Generated by Django 2.0.5 on 2018-05-28 11:10

from django.db import migrations


def default_problems(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    problem_1000 = Problem(
        pk=1000,
        title="A+B Problem",
        time_limit=1.0,
        memory_limit=256.0,
        description=r""" \
===========
A+B Problem
===========
:Problem ID: 1000
:Time Limit: 1 S
:Memory Limit: 128 MB

Problem
-------
Input two number *a* and *b*

Output *a + b*

Examples
--------
0. Input: ::

   1 1

Output: ::

   2
1. Input: ::

   15 5

Output: ::

   20

Data Range
----------
:math:`a+b<=2^{31}-1`

--------------------------------

Solutions
---------
C Language
~~~~~~~~~~
.. code:: C

   # include <stdio.h>
   int main()
   {
       int a, b;
       scanf("%d%d", &a, &b);
       printf("%d\n", a + b);
       return 0;
   }

C++ Language
~~~~~~~~~~~~
.. code:: cpp

   # include <iostream>
   int main()
   {
       int a, b;
       std::cin >> a >> b;
       std::cout << a + b << std::endl;
       return 0;
   }

""",
        submissions=0,
        accpected=0,
    )
    problem_1000.save()


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_description'),
    ]

    operations = [
        migrations.RunPython(default_problems),
    ]
