# Generated by Django 2.0.5 on 2018-05-29 14:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_testcase'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='problem',
            managers=[
                ('problems_set', django.db.models.manager.Manager()),
            ],
        ),
    ]
