# Generated by Django 2.0.5 on 2018-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=512)),
                ('phone_number', models.DecimalField(decimal_places=11, max_digits=11)),
                ('email', models.EmailField(max_length=254)),
                ('register_time', models.DateTimeField()),
            ],
        ),
    ]
