# Generated by Django 2.0.5 on 2018-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
