# Generated by Django 2.0.5 on 2018-05-30 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++')], editable=False, max_length=4)),
                ('code', models.TextField(editable=False)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('running_time', models.DurationField(editable=False)),
                ('problem', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.Problem')),
            ],
            options={
                'permissions': (('view_record', 'View all records.'),),
            },
            managers=[
                ('records_set', django.db.models.manager.Manager()),
            ],
        ),
    ]
