# Generated by Django 2.0.5 on 2018-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20180602_1634'),
        ('records', '0002_record_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': (('view_all_records', 'View all records.'),)},
        ),
        migrations.AddField(
            model_name='record',
            name='result_per_test_case',
            field=models.ManyToManyField(to='problems.TestCase'),
        ),
        migrations.AlterField(
            model_name='record',
            name='language',
            field=models.CharField(choices=[('gcc', 'C (gcc)'), ('g++', 'C++ (g++)')], editable=False, max_length=4),
        ),
    ]
