# Generated by Django 2.0.5 on 2018-05-29 14:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180529_2227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='record',
            managers=[
                ('records_set', django.db.models.manager.Manager()),
            ],
        ),
    ]
