# Generated by Django 2.0.6 on 2018-06-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180605_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.TestCase'),
        ),
    ]
