# Generated by Django 2.0.6 on 2018-06-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20180610_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseresult',
            name='test_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.TestCase'),
        ),
    ]
